#!/bin/sh
CACHE_DIR="$XDG_CACHE_HOME/murl"
SUB_DIR="$CACHE_DIR/subs"
URL_TEMP="$CACHE_DIR/temp_url.json"
URL_HIST="$CACHE_DIR/hist_url.json"
VIDEO_URL=("www.youtube.com" "lbry.tv" "www.bilibili.com")
STREAM_URL=("live.bilibili.com" "www.huya.com" "www.douyu.com")
CLIPBOARD=$(xclip -sel clipboard -o 2>/dev/null)
PROXY="export http_proxy=http://127.0.0.1:1088 https_proxy=http://127.0.0.1:1088"
TEMPLATE_TEMP="[{\"title\":\" Clear\",\"cmd\":\"rm $URL_TEMP\"},{\"title\":\" All\",\"cmd\":\"mpv_url hist\"}]"
TEMPLATE_HIST="[{\"title\":\" Clear All\",\"cmd\":\"rm $URL_HIST\"},{\"title\":\" Temp\",\"cmd\":\"mpv_url temp\"}]"

_try_add_url() {
  URL=$CLIPBOARD; __notify_once
  [[ "$host" == "www.bilibili.com" ]] && __handle_bilivideo
  [[ "$host" == "live.bilibili.com" ]] && __handle_bililive
  URL_TITLE=$(__get_title $URL)
  [[ -z $(grep $CLIPBOARD $URL_TEMP) ]] && __add_url $URL_TEMP true
  [[ -z $(grep $CLIPBOARD $URL_HIST) ]] && __add_url $URL_HIST false
}
_rofi() { rofi -multi-select -theme ~/.config/rofi/themes/launcher.rasi -p "$1" -dmenu; }
_host() { echo $@ | awk -F[/:] '{print $4}'; }
_global_action() {
   cmd=$(jq --arg t "$chosen" '.[] | select(.title == $t) | .cmd' $LIST | tr -d '"')
   eval "$cmd"
}
_url_action() {
  chosen_action=$(echo -e "Play\nDelete" | _rofi "Action:")
  url=$(jq --arg t "$chosen" '.[] | select(.title == $t) | .url' $LIST | tr -d '"')
  case $chosen_action in
    Play) __play_url;;
    Delete) __delete_url;;
  esac
}

__get_title() { curl -sL ${HEADER[@]} $1 | pup --charset utf8 -p 'title text{}'; }
__notify_once() {
  test -z $(grep $URL $CACHE_DIR/notify) && \
  __notify "Try add..." "$URL"; echo $URL >> $CACHE_DIR/notify
}
__add_url() {
  echo $(__updated_list "$1") > "$1"
  $2 && __notify "Added to playlist" "$URL_TITLE"
}
__handle_bilivideo() {
  HEADER=(-H "User-Agent: Mozilla/5.0 (Android 6.0;)")
  bv_num=$(awk -F[:/?] '{print $6}' <<< $CLIPBOARD)
  vid_info=$(curl https://api.bilibili.com/x/player/pagelist?bvid="$bv_num"\&jsonp=jsonp)
  cid=$(jq '.data[0].cid' <<< $vid_info)
  curl -G 'http://api.bilibili.com/x/v1/dm/list.so' \
    --data-urlencode oid=$cid \
    --compressed -o $SUB_DIR/"$bv_num".xml
  danmaku2ass -s 1280x720 -fs 30 -a 0.5 -o $SUB_DIR/"$bv_num".ass $SUB_DIR/"$bv_num".xml
  rm $SUB_DIR/"$bv_num".xml
  SUB="$SUB_DIR/$bv_num.ass"
}
__handle_bililive() {
  HEADER=(-H "User-Agent:Chrome/50")
  URL=$(awk -F? '{print $1}' <<< $URL)
}
__notify() { notify-send.py -i mpv -a mpv --replaces-process mpv "$1" "$2" & disown; }
__updated_list() {
  jq --arg t "$URL_TITLE" --arg u "$URL" --arg s "$SUB" \
  '.[length] = {"title":$t,"url": $u,"sub":$s}|unique' "$1"
}
__play_url() {
  host=$(_host $url)
  subfile=$(jq --arg u "$url" '.[] | select(.url == $u) | .sub' $LIST | tr -d '"')
  [[ -n $subfile ]] && sub_flag="--sub-file=$subfile"
  [[ "${STREAM_URL[@]}" == *"$host"* ]] && exec qlphelper --fa 0.6 -u "$url" \
  || exec mpv "$sub_flag" "$url"
}
__delete_url() {
  new_list=$(jq --arg u "$url" '.[] | select(.url != $u)' $LIST | jq -s)
  echo $new_list > $LIST
}

main() {
  [ -d $CACHE_DIR ] || mkdir -p $CACHE_DIR
  [ -d $SUB_DIR ] || mkdir $SUB_DIR
  [ -f $URL_TEMP ] || echo "$TEMPLATE_TEMP" > $URL_TEMP
  [ -f $URL_HIST ] || echo "$TEMPLATE_HIST" > $URL_HIST
  eval "$PROXY"
  all_url=("${VIDEO_URL[@]}" "${STREAM_URL[@]}") host=$(_host $CLIPBOARD)
  [[ -n "$host" ]] && [[ "${all_url[@]}" == *"$host"* ]] && _try_add_url
  [[ -z "$@" ]] && exit
  LIST=$URL_TEMP; [ $1 == 'hist' ] && { LIST=$URL_HIST PMT_HIST="(all)"; }
  chosen=$(jq '.[] .title' $LIST | tr -d '"' | _rofi "Choose$PMT_HIST:")
  case $chosen in
    "") exit 0;;
    *) _global_action;;
    *) _url_action;;
  esac
}

main "$@"
